name: Xamarin
on: push



jobs:
  Android:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        
        dotnet restore
        cd VokabelCarsten
        msbuild VokabelCarsten.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
