name: Xamarin - Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup dotNET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: restore
      run: nuget restore
    - name: builld dotNET
      run: dotnet build --configuration Debug
