name: Xamarin
on: [push, pull_request]



jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd VokabelCarsten
        nuget restore
        cd VokabelCarsten
        msbuild VokabelCarsten.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
