name: Xamarin.Android

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Build App
      run: |
            cd VokabelCarsten.Android
            msBuild VokabelCarsten.Android.csproj -t:restore -t:Package
    - uses: actions/upload-artifact@v1
      with:
        name: Build_Results
        path: ../Build/
