name: Xamarin

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Restoring Packages
      run: |
                cd VokabelCarsten.Android
                msBuild -t:restore
    - name: Build App
      run: |
                cd VokabelCarsten.Android
                msBuild VokabelCarsten.Android.csproj
  test:
    runs-on: windows-latest
    steps:
    - name: Setup MSTest.exe
      run: |
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\MSTest.exe
    
