name: Xamarin

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Restoring Packages
      run: |
                cd VokabelCarsten.Android
                msBuild -t:restore
    - name: Build App
      run: |
                cd VokabelCarsten.Android
                msBuild VokabelCarsten.Android.csproj
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSTest.exe
      uses: SariusRu/Setup-MSTest@v2
    - name: Restoring Packages
      run: |
                cd VokabelCarsten.Test
                msBuild -t:restore
    - name: Build App
      run: |
                cd VokabelCarsten.Test
                msBuild VokabelCarsten.Test.csproj
